---

name: Mypy

on:
  push:
    branches-ignore:
      - auto-backport-of-pr-[0-9]+
      - v[0-9]+.[0-9]+.[0-9x]+-doc
  pull_request:

jobs:
  test:
    name: "Mypy"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Set up reviewdog
        run: |
          mkdir -p "$HOME/bin"
          curl -sfL \
            https://github.com/reviewdog/reviewdog/raw/master/install.sh | \
              sh -s -- -b "$HOME/bin"
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade mypy

      - name: Install cycler
        run: |
          python -m pip install --no-deps -e .

      - name: Run mypy
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mypy cycler test_cycler.py | \
            reviewdog -f=mypy -name=mypy \
              -tee -reporter=github-check -filter-mode nofilter
